// <auto-generated />
namespace TaskManagementAppNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v3_addSubtask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3_addSubtask));
        
        string IMigrationMetadata.Id
        {
            get { return "202305130423212_v3_addSubtask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
