// <auto-generated />
namespace TaskManagementAppNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v2_addtask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_addtask));
        
        string IMigrationMetadata.Id
        {
            get { return "202305110310014_v2_addtask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
